permissions:
  contents: write

name: release
on:
  push:
    tags: ["v*"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-linux-gnu
            pack: tar
          - os: ubuntu-latest
            target: x86_64-linux-musl
            pack: tar
          - os: ubuntu-latest
            target: aarch64-linux-musl
            pack: tar
          # macOS
          - os: macos-latest
            target: aarch64-macos
            pack: tar
          - os: macos-13
            target: x86_64-macos
            pack: tar

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with: { version: 0.15.1 }

      - name: Cache Zig caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/zig
            zig-cache
            zig-out
          key: ${{ runner.os }}-zig-0.15.1-${{ hashFiles('build.zig', 'build.zig.zon', 'src/**/*.zig') }}

      - name: Build (Release)
        shell: bash
        run: |
          VER=${GITHUB_REF_NAME#v}
          zig build -Doptimize=ReleaseFast -Dstrip=true -Dcpu=baseline -Dtarget=${{ matrix.target }} -Dversion=$VER

      - name: Package artifact
        shell: bash
        run: |
          set -euxo pipefail
          VER=${GITHUB_REF_NAME#v}
          OUT=stringer-$VER-${{ matrix.target }}
          rm -rf "$OUT"
          mkdir -p "$OUT"
          cp zig-out/bin/stringer "$OUT"/
          cp README.md LICENSE "$OUT"/ 2>/dev/null || true
          tar -czf "$OUT".tar.gz "$OUT"
          echo "$OUT.tar.gz" >> artifact_list.txt

      - name: Upload per-target artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.target }}
          path: |
            *.tar.gz
            *.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist*
          merge-multiple: true 
          path: dist

      - name: Generate SHA256SUMS.txt
        working-directory: dist
        run: |
          shopt -s nullglob
          sha256sum *.tar.gz > SHA256SUMS.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/SHA256SUMS.txt
          draft: false
          prerelease: false
